version: "3.8"
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
  myblog:
    build: ./myblog
    container_name: myblog_c
    ports:
      - "3001:3001"
    volumes:
      - ./myblog:/app
      - /app/node_modules
    stdin_open: true
    tty: true
